spring.data.jpa.repositories.enabled: true
spring.datasource.url: jdbc:mysql://localhost:3306/geo_db
spring.datasource.username: root
spring.datasource.password: daniel.51
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.pool-size: 30
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans: true
spring.jpa.hibernate.ddl-auto: update
server.port: 8080
server.servlet.context-path: /geo
info.app.name: Geo
info.app.description: Geo application store info about states, neighbors , cp
info.app.version: 1.0.0
management.endpoint.metrics.enabled: true
management.endpoint.httptrace.enabled: true
management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: health,info,metrics,httptrace
management.endpoints.web.cors.allowed-origins: http://localhost:3000
management.endpoints.web.cors.allowed-methods: GET,POST
#env: default
minio.user: minio
minio.accesskey: minio123
minio.url: http://127.0.0.1:9001/minio/

# Local Elasticsearch config
spring.data.elasticsearch.repositories.enabled: true
spring.data.elasticsearch.cluster-nodes: localhost:9300
spring.data.elasticsearch.cluster-name: docker-cluster

#logging config
#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.howtodoinjava: DEBUG
#    org.hibernate: ERROR
#    pattern:
#        console: \%d{yyyy-MM-dd HH:mm:ss} - %msg%n
#        file: \%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#spring:
#    output:
#    ansi:
#        enabled: DETECT
