server:
  port: 5555

spring:
  application:
    name: zuulms
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: health,info,routes,filters
      
zuul:
    prefix: /api
    routes:
      geoms: /geo/**
