version: '3.5'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'geo_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'geoUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'daniel.51'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'daniel.51'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - geo-db:/var/lib/mysql
    networks:
      - geo_network
      
# Names our volume
volumes:
  geo-db:
  
networks:
  geo_network:
    name: geo_network
    #external: true