version: '3.5'
services:
  confsvr:
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '8888:8888'
    expose:
      - '8888'
    networks:
      - geo_network
networks:
   geo_network:
    name: geo_network