version: '3.0'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - geo_network
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - geo_network
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - geo_network
    environment:
      # SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    #depends_on:
    #  - elasticsearch

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  geo_network:
    external: true